### ISSUE TITLE
自助添加k8s集群的时候，无法根据现在的界面来添加

### ISSUE THREAD

**Issue by c4fun** [erda-project/erda#1037]
#### What happened:
自助添加k8s集群的时候，无法根据现在的界面来添加

#### What you expected to happen:
添加集群的时候，泛域名和集群入口能够有相应的提示，并且能够配置

#### How to reproduce it (as minimally and precisely as possible):
1. 在同一个网络中，通过kubeasz创建另外一个K8S集群。
2. 通过erda的[安装指导](https://github.com/erda-project/erda/blob/master/docs/guides/deploy/How-to-install-Erda-zh.md)安装好erda，然后通过管理员创建一个erda-test的租户，再登录到erda-test-org.erda.io这个租户里面。
3. 参考了[这个指导](https://docs.erda.cloud/1.1/manual/o_m/create-cluster.html#%E4%BA%8B%E5%89%8D%E5%87%86%E5%A4%87)，在多云管理平台-->资源管理-->集群管理中，添加集群-->导入已创建的Erda Kubernetes集群。根据界面来填写时，发现泛域名和集群入口不能够直接拿我们K8S节点的IP地址。
![image](https://user-images.githubusercontent.com/5254836/125884194-fd4870ab-702b-4509-ad5b-83cee7d23dc8.png)

#### Anything else we need to know?:
目前erda能够导入的K8S集群，只能够是erda自身创建的吗？能否导入外部的集群？

我现在主要是想要体验一下erda的各种功能；如果不添加额外的K8S集群，是否可以用erda目前所在的集群做DevOps、部署这类的操作呢？

#### Environment:
- Erda version: 1.0.1
- Kubernetes version (use `kubectl version`): v1.18.16
- Cloud provider or hardware configuration:  tencent cloud
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.9.2009
- Kernel (e.g. `uname -a`): 3.10.0-1160.31.1.el7.x86_64
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Muzry** [comment]
> #### What happened:
> 自助添加k8s集群的时候，无法根据现在的界面来添加
> 
> #### What you expected to happen:
> 添加集群的时候，泛域名和集群入口能够有相应的提示，并且能够配置
> 
> #### How to reproduce it (as minimally and precisely as possible):
> 1. 在同一个网络中，通过kubeasz创建另外一个K8S集群。
> 2. 通过erda的[安装指导](https://github.com/erda-project/erda/blob/master/docs/guides/deploy/How-to-install-Erda-zh.md)安装好erda，然后通过管理员创建一个erda-test的租户，再登录到erda-test-org.erda.io这个租户里面。
> 3. 参考了[这个指导](https://docs.erda.cloud/1.1/manual/o_m/create-cluster.html#%E4%BA%8B%E5%89%8D%E5%87%86%E5%A4%87)，在多云管理平台-->资源管理-->集群管理中，添加集群-->导入已创建的Erda Kubernetes集群。根据界面来填写时，发现泛域名和集群入口不能够直接拿我们K8S节点的IP地址。
>    ![image](https://user-images.githubusercontent.com/5254836/125884194-fd4870ab-702b-4509-ad5b-83cee7d23dc8.png)
> 
> #### Anything else we need to know?:
> 目前erda能够导入的K8S集群，只能够是erda自身创建的吗？能否导入外部的集群？
> 
> 我现在主要是想要体验一下erda的各种功能；如果不添加额外的K8S集群，是否可以用erda目前所在的集群做DevOps、部署这类的操作呢？
> 
> #### Environment:
> * Erda version: 1.0.1
> * Kubernetes version (use `kubectl version`): v1.18.16
> * Cloud provider or hardware configuration:  tencent cloud
> * OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.9.2009
> * Kernel (e.g. `uname -a`): 3.10.0-1160.31.1.el7.x86_64
> * Network plugin and version (if this is a network-related bug):
> * Others:

1.0.x 版本还无法导入非 erda 创建的集群，该问题会在 1.1.x 版本解决。可以通过导入当前的 erda 所在的 k8s 集群，成功导入后可以正常使用 devops 和部署的操作

**Comment by c4fun** [comment]
可以问下当前erda所在K8S集群的泛域名和集群入口填写什么吗？我们目前这个k8s集群没有加域名，直接使用的IP。clusterinfo的信息如下：

```
# kubectl cluster-info
Kubernetes master is running at https://10.113.25.3:6443
KubeDNS is running at https://10.113.25.3:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```

我试了一下添加erda-test-org.erda.io，但添加出来有问题，erda无法识别node：
![image](https://user-images.githubusercontent.com/5254836/125886988-0318b503-59e2-46b8-a5fb-029600694ded.png)

**Comment by Muzry** [comment]
> 可以问下当前erda所在K8S集群的泛域名和集群入口填写什么吗？我们目前这个k8s集群没有加域名，直接使用的IP。clusterinfo的信息如下：
> 
> ```
> # kubectl cluster-info
> Kubernetes master is running at https://10.113.25.3:6443
> KubeDNS is running at https://10.113.25.3:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
> ```
> 
> 我试了一下添加erda-test-org.erda.io，但添加出来有问题，erda无法识别node：
> ![image](https://user-images.githubusercontent.com/5254836/125886988-0318b503-59e2-46b8-a5fb-029600694ded.png)

- 泛域名地址请按照部署时配置信息填写
- 集群入口信息请填写：`inet://ingress-nginx.kube-system.svc.cluster.local?direct=on&ssl=on/kubernetes.default.svc.cluster.local`

**Comment by c4fun** [comment]
请问一下添加了集群之后，还需要自行添加机器对吧？
添加机器的时候，报这个错误，跟前面集群是否建立好是否有关系？
![image](https://user-images.githubusercontent.com/5254836/126476026-b5bfd42b-b631-4b34-9573-2f919876d98c.png)

![image](https://user-images.githubusercontent.com/5254836/126475871-34716ab7-ae9f-4251-b97e-f90aad0d26d9.png)

**Comment by Muzry** [comment]
@c4fun 抱歉未及时回复，看上去是没有正确的推送 action 导致这个报错。请问是否执行了安装文档中的 push-ext 步骤？
