### ISSUE TITLE
admin管理员不可创建集群

### ISSUE THREAD

**Issue by c4fun** [erda-project/erda#1038]
#### What happened:
在当前的管理员视图中(通过admin登录erda.io)，不能够创建集群。

#### What you expected to happen:
管理员应该可以创建集群，这样能够减轻组织自行创建集群的负担。
如果必须到组织才能创建集群，请也在前台给出明显提示，并且告知原因为什么不可以创建。

#### How to reproduce it (as minimally and precisely as possible):

1. 安装好之后，管理员登录erda.io
2. 进入管理后台界面，尝试创建集群，发现界面置灰。
![image](https://user-images.githubusercontent.com/5254836/125885140-cab66f22-419a-41a4-9789-416dade53f3d.png)

#### Environment:
- Erda version: 1.0.1
- Kubernetes version (use `kubectl version`): v1.18.16
- Cloud provider or hardware configuration: tencent cloud
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.9.2009
- Kernel (e.g. `uname -a`): 3.10.0-1160.31.1.el7.x86_64
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by huangzx618** [comment]
你好，首先非常感谢反馈问题，
关于 admin 后台页面目前只是一个简单的管理页面，主要是用于解决组织的创建管理的问题，
但是随着 V 1.1 版本中支持了非 admin 用户自助创建组织的特性发布后，
目前的 admin 后台页面也没有那么必要了，
所以这块内容我们后期会规划定位为平台后台运营管理，主要运营管理平台资源、组织租户的计量分析等功能，
到这个时候一定会有平台层集群资源的管理。
具体的内容可以关注 Erda 后期的规划动向，谢谢！

解释完目前 admin 后台页面后，对于目前为什么没有支持集群管理的原因，
1. 目前平台没有针对所有组织提供统一的集群资源池，不支持用户按需申请使用，
    所有的集群资源都是租户自己创建管理的，所以目前就放在组织租户的多云管理中来完成的
2. 放在组织的多云管理中还有另外一个原因就是集群创建的时候，相关组织标签都是已经设置的，不需要额外进行标签设置

**Comment by c4fun** [comment]
好的，谢谢。
请问在哪里可以关注Erda后期的规划动向呢，谢谢

**Comment by huangzx618** [comment]
你好，当前我们在微信群中会公布我们近期迭代的内容，稍微后面一点我们会在 GitHub 中维护更新 Roadmap，谢谢！
