### ISSUE TITLE
cmp中的4个组件分别是什么含义

### ISSUE THREAD

**Issue by fishdemon** [erda-project/erda#1374]
cluster-manage: 我理解是控制端用来管理集群，集群的增删改查
cluster-init
cluster-agent
cluster-dialer 
这几个的作用是什么？

**Comment by johnlanni** [comment]
cluster-init: 集群导入时的初始化安装
cluster-agent：远端集群内的 agent，用于和 erda 的控制平面建立 websocket 管控通道
cluster-dialer：其他 erda 组件可以通过访问此模块的接口，来调用远端集群内的服务

另外，cluster-agent 和 cluster-dialer 都是独立的服务模块，并不属于 CMP

**Comment by iutx** [comment]
cluster-init 在 1.1.2 版本以后将替换为 cluster-ops
用于 work 集群的初始化以及升级
