### ISSUE TITLE
急～执行scripts/push-ext.sh 找不到这个服务openapi.default.svc.cluster.local

### ISSUE THREAD

**Issue by duanbingu** [erda-project/erda#1391]
kubectl get svc -A 没有该服务
![image](https://user-images.githubusercontent.com/47857453/128898231-45eea0cd-b562-46bd-a57c-c74845ec03bd.png)

执行push-ext.sh 错误提示：
![image](https://user-images.githubusercontent.com/47857453/128898177-e5ba1ca5-68b6-4f8a-8571-6738b532c19c.png)

并且pod有不少也没有启动起来
![image](https://user-images.githubusercontent.com/47857453/128898545-3b81ad38-833b-495a-a092-322f5725332d.png)

helm 也都安装了。
![image](https://user-images.githubusercontent.com/47857453/128898640-c124710c-ae0a-4c67-8075-e00234c9fcef.png)

Erda version: 1.1.1
Kubernetes version (use kubectl version): v1.18.6
Cloud provider or hardware configuration:huaweiyun cloud
OS (e.g: cat /etc/os-release): CentOS Linux release 7.6.1810

**Comment by luobily** [comment]
需要等待 helm install erda 对应的组件安装起来，openapi 还没起来，所以报错了。
