### ISSUE TITLE
添加已有集群报错

### ISSUE THREAD

**Issue by spar4s** [erda-project/erda#1406]
What happened:
导入已有集群报错
#### What you expected to happen:
能够通过界面导入一个已有的k8s集群
#### How to reproduce it (as minimally and precisely as possible):
多云管理平台 ->添加集群 -> 导入已创建的Erda Kubernetes集群 
![image](https://user-images.githubusercontent.com/17963921/129028547-51eccfab-1f57-4140-8156-8488cbf0f089.png)

![image](https://user-images.githubusercontent.com/17963921/129028875-ca692766-1fae-47f8-944f-8965adb54780.png)

Environment:
- Erda version: 1.1.1
- Kubernetes version (use `kubectl version`): 1.18.20
- Cloud provider or hardware configuration: vmware vsphere
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.6.1810 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-957.el7.x86_64
- Network plugin and version (if this is a network-related bug): calico 3.20.0
- Others:

**Comment by luobily** [comment]
泛域名配置的有问题，是个 * 通配域名，和你安装 erda 时配置的域名一致，例如： “*.erda.io”。

不过应该不是报错的原因。
/cc @iutx

**Comment by iutx** [comment]
@spar4s 您好，经过复现，该问题可能与您 Erda 安装的 namespace 有关系，当前 Erda 只支持安装在 default namespace 下，请确认下当前所部署的 namespace 是否是 default，近期我们会发布新的小版本支持其他namespace。
