### ISSUE TITLE
关于步骤三helm install下载失败的问题

### ISSUE THREAD

**Issue by wqone900516** [erda-project/erda#1421]
#### What happened:
在安装到步骤三的时候，执行说明中的步骤：
helm install erda-base package/erda-base-$(cat VERSION).tgz
无法下载包
![image](https://user-images.githubusercontent.com/39078409/129212105-a3b9963a-7b0b-4606-aa20-55fc107e35cd.png)

#### What you expected to happen:
可以顺利安装试用

#### Environment:
- Erda version:1.1.1
- Kubernetes version (use `kubectl version`):1.17.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):Centos7.8
- Kernel (e.g. `uname -a`):
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wqone900516** [comment]
我尝试了一下使用安装包中自带的erda-base，是否是需要将下载的erda-base上传到自建的helm中，然后再进行安装？
是否可以告知如何用helm安装下载包中的erda-base呢？
另外还尝试了一下在erda目录下 用helm install erda-base --generate-name --dry-run --debug命令进行验证，发现有报错信息，如下所示，请问如何解决，非常感谢！！！
![image](https://user-images.githubusercontent.com/39078409/129236706-64230a5e-d862-4941-8d63-dbe0399555b5.png)

**Comment by luobily** [comment]
不需要下载，我们现在采用的是本地 helm 包进行安装。存在多层模版渲染，需要先执行 `bash scripts/prepare.sh` 命令，会生成本地安装包。
我们正在优化 helm chart，近期会输出远端仓库下载的方式。

**Comment by wqone900516** [comment]
> 不需要下载，我们现在采用的是本地 helm 包进行安装。存在多层模版渲染，需要先执行 `bash scripts/prepare.sh` 命令，会生成本地安装包。
> 我们正在优化 helm chart，近期会输出远端仓库下载的方式。

多谢，已找到问题根源，bash scripts/prepare.sh 执行一下就可以了，此问题可以关闭，谢谢！
