### ISSUE TITLE
Erda dashboard value view problem

### ISSUE THREAD

**Issue by luoyuctl** [erda-project/erda#1439]
#### What happened:
 when value below 0.005 percent, dashboard value round down view will not be readable. 
![image](https://user-images.githubusercontent.com/51604064/129481399-89edcdfa-4e59-4990-be52-87dc63392f9d.png)

#### What you expected to happen:
round down like 0.00 or other readable type.

#### Environment:
- Erda Cloud

**Comment by liuhaoyang** [comment]
Please submit the front-end issue to [Erda-UI repo](https://github.com/erda-project/erda-ui).

**Comment by luoyuctl** [comment]
https://github.com/erda-project/erda-ui/issues/946
