### ISSUE TITLE
Go action support dynamic go version or higher version 

### ISSUE THREAD

**Issue by luoyuctl** [erda-project/erda#1470]
#### What would you like to be added:
1.support go build action module go version dynamic or be optional.
2.Increase the display of the current go version and other language version in the action to facilitate the location of problems.

#### Why is this needed:

some feature is not support , like 1.16 feature “go embed”.

![image](https://user-images.githubusercontent.com/51604064/129659919-c0d1f78d-c637-4a4f-8e99-9198ac24a415.png)

**Comment by chengjoey** [comment]
Thank you for your suggestion, we have upgraded Go action, go version: 1.16.7, merged [pr](https://github.com/erda-project/erda-actions/pull/156)

you could do these to update go action:
```
dice ext pull
dice ext push 
```
