### ISSUE TITLE
如何在没有域名的情况下，外网访问erda.io？

### ISSUE THREAD

**Issue by wqone900516** [erda-project/erda#1492]
#### What happened:
已完成k8s集群搭建，应用已经部署，ingress-controller已经安装，由于没有域名，有外网可访问的IP地址，配置了一台master三台node，不知如何配置ingress-controller才可以使外网访问到，已试过用master节点外网ip地址访问，无效。

![image](https://user-images.githubusercontent.com/39078409/129779122-e481066c-8f6d-4e36-b38f-59c3a013c521.png)
![image](https://user-images.githubusercontent.com/39078409/129779277-20f960dc-2585-497d-ae9b-95e69adb75f8.png)

#### What you expected to happen:
可以通过配置外网IP+端口访问到erda平台，谢谢。

#### Environment:
- Erda version:
- Kubernetes version (use `kubectl version`): 1.17.0
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wqone900516** [comment]
更新：目前遇到的问题是，所有应用容器工作负载都已经正常启动，ingress-nginx-controller也已经安装，但是无法找到文档说的入口IP地址，包括安装ingress-nginx-controller的node的外网IP和内网IP以及nodeip都已经试过了，都不行。
是否有直接访问外网IP的方法，可以先能访问到，我们想先打通再考虑域名的事情，非常感谢。
![image](https://user-images.githubusercontent.com/39078409/129833512-923f5bbe-1b47-48d7-8116-87abae4c722d.png)

**Comment by liuhaoyang** [comment]
可以按照文档写的域名配置，本地添加 hosts 来访问

**Comment by luobily** [comment]
最终是要把域名的访问流量给导入到 ingress controller 中，你可以理解为该 controller 就是一个 nginx，你的场景就是需要解决公网 IP + 80 / 443 端口，如何转到该 nginx 上。
这个具体要看自己的部署方式，有个简单的方式就是选择一台机器，然后将该 ingress controller 部署成 host 模式，直接将 controller 的 80/443 端口监听在宿主机上，接着将该公网 IP 绑定在同一台机器上，就可以通过 公网IP + 80 /443 端口直接访问。
