### ISSUE TITLE
集群安装失败

### ISSUE THREAD

**Issue by yuezheng** [erda-project/erda#1625]
![image](https://user-images.githubusercontent.com/1791214/131502887-b6ca485c-46d9-4888-8606-1b03a9144dd8.png)直接在页面上创建集群，选择创建阿里云托管版集群，资源都已经创建完成，在安装dice的步骤失败。

另外一种方式安装，基于Helm，在阿里云ACK集群中安装，也是安装失败:
![image](https://user-images.githubusercontent.com/1791214/131527320-ffc86b11-6e37-4a63-987c-4b82221c76ae.png)

**Comment by iutx** [comment]
@yuezheng 第二种安装方式，erda 资源是 Running的，代表 Erda 组件全部安装完成并状态正常。
