### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [erda-project/erda#1802]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by hoozecn** [comment]
Hi @JamieSlome, thanks for your info. 

You can contact us with the email [erda@terminus.io](mailto:erda@terminus.io) which is also present in [readme.md ](https://github.com/erda-project/erda#contact-us). Thx

**Comment by hoozecn** [comment]
Close this issue for now. Please don't hesitate to reopen it if you have further public request.

**Comment by JamieSlome** [comment]
@hoozecn - just a heads up that the report can be found here:

https://www.huntr.dev/bounties/6b77bb0c-3eb1-4bcc-a2a3-9b3341c34970/

It is private and only visible to maintainers with repository write permissions 👍 Let me know if you have any further questions.
