### ISSUE TITLE
基于k8s部署后，集群总览中没有实例数显示。

### ISSUE THREAD

**Issue by Climber2017** [erda-project/erda#2075]
#### 基于k8s部署后，集群总览中没有实例数显示。

![image](https://user-images.githubusercontent.com/33715647/134511769-0bef4e80-f9db-48f4-afbc-727648102b21.png)

以下是telegraf pod的logs信息：
![image](https://user-images.githubusercontent.com/33715647/134511945-484b074c-0178-47f1-896b-c76a5f814cbe.png)

**Comment by erenming** [comment]
嗨，看情况估计是挂载问题。
默认情况下，telegraf会挂载节点的根目录`/:/rootfs:ro`，您可以通过以下步骤排查：
1. 检查telegraf的volume挂载是否正确，可通过`kubectl get po -o yaml erda-telegraf-xxx`来查看
2. 检查docker.sock文件是否位于主机目录的`/var/run`下

**Comment by Climber2017** [comment]
> 嗨，看情况估计是挂载问题。 默认情况下，telegraf会挂载节点的根目录`/:/rootfs:ro`，您可以通过以下步骤排查：
> 
> 1. 检查telegraf的volume挂载是否正确，可通过`kubectl get po -o yaml erda-telegraf-xxx`来查看
> 2. 检查docker.sock文件是否位于主机目录的`/var/run`下

嗨，你好老师，感谢您的回复，按照您的提示进行了查找，如下：
1.目录挂载没有问题
![image](https://user-images.githubusercontent.com/33715647/135374094-0f06d48d-8e20-424d-b94b-240279e9dad0.png)
![image](https://user-images.githubusercontent.com/33715647/135374140-8b5cde51-f416-4db7-9c1e-d56469461019.png)
![image](https://user-images.githubusercontent.com/33715647/135374172-1f4fc562-78dd-46ac-9298-6d798f49c710.png)

2.docker.sock也在/var/run下
![image](https://user-images.githubusercontent.com/33715647/135374281-30673219-a7d7-42f4-ae88-bd00e764c054.png)

老师，还有可能需要排除或者修改的地方吗?

**Comment by erenming** [comment]
> > 嗨，看情况估计是挂载问题。 默认情况下，telegraf会挂载节点的根目录`/:/rootfs:ro`，您可以通过以下步骤排查：
> > 
> > 1. 检查telegraf的volume挂载是否正确，可通过`kubectl get po -o yaml erda-telegraf-xxx`来查看
> > 2. 检查docker.sock文件是否位于主机目录的`/var/run`下
> 
> 嗨，你好老师，感谢您的回复，按照您的提示进行了查找，如下： 1.目录挂载没有问题 ![image](https://user-images.githubusercontent.com/33715647/135374094-0f06d48d-8e20-424d-b94b-240279e9dad0.png) ![image](https://user-images.githubusercontent.com/33715647/135374140-8b5cde51-f416-4db7-9c1e-d56469461019.png) ![image](https://user-images.githubusercontent.com/33715647/135374172-1f4fc562-78dd-46ac-9298-6d798f49c710.png)
> 
> 2.docker.sock也在/var/run下 ![image](https://user-images.githubusercontent.com/33715647/135374281-30673219-a7d7-42f4-ae88-bd00e764c054.png)
> 
> 老师，还有可能需要排除或者修改的地方吗?

可以进入问题容器，使用命令`curl --unix-socket /rootfs/var/run/docker.sock http:/containers/json`，检测docker.sock能否连通
