### ISSUE TITLE
when i change my password ，cursor is missing

### ISSUE THREAD

**Issue by ThomasJLasky** [erda-project/erda#268]
#### What happened:
![image](https://user-images.githubusercontent.com/22903680/116338547-7a4ff100-a80e-11eb-8783-708d372b0578.png)
![image](https://user-images.githubusercontent.com/22903680/116338689-b97e4200-a80e-11eb-856e-b4b4145b5f8d.png)

when i type first word , the cursor will missing
#### What you expected to happen:
User experience optimization

**Comment by luoyuctl** [comment]
Same issue found , i 'll forward to the responsible person.

**Comment by luoyuctl** [comment]
Has been conveyed, repaired, thanks for the suggestion.

**Comment by luoyuctl** [comment]
Has been conveyed, repairing , thanks for the suggestion.
