### ISSUE TITLE
可以给一个线上demo体验一下嘛，不要这种图片demo骗我们

### ISSUE THREAD

**Issue by adseng** [erda-project/erda#2729]

**Comment by sfwn** [comment]
可以访问 [Erda Cloud Playgroud](https://erda.cloud/playground) 进行体验 :P

**Comment by adseng** [comment]
> 可以访问 [Erda Cloud Playgroud](https://erda.cloud/playground) 进行体验 :P

多谢

**Comment by sfwn** [comment]
I will close it. Feel free to create new issues if you encounter problems later. Thanks.

**Comment by alexzhu0592** [comment]
website is collapse 😭 

> {
>    "success": false,
>    "error": "server.error"
> }
