### ISSUE TITLE
erda's status failed : create init jobs failed: Job has reached the specified backoff limit

### ISSUE THREAD

**Issue by sayicui** [erda-project/erda#3272]
#### What happened:
When I installed erda by Helm, the status of erda is failed and cannot go on.
In the erda-system namespace, only the middleware pod, there are no erda's pod.
And there's no pod in default namespace.
![image](https://user-images.githubusercontent.com/27839478/144747127-2912b83d-e53b-4daf-8e34-3dc5a0791782.png)

![image](https://user-images.githubusercontent.com/27839478/144747139-f193c151-fe9b-425d-9e94-7eb321cd821c.png)

![image](https://user-images.githubusercontent.com/27839478/144747145-aaf55c5d-9c48-41a7-b43f-988d3ff080aa.png)

#### Environment:
- Erda version: 1.4
- Kubernetes version (use `kubectl version`): 1.21.6
- Cloud provider or hardware configuration:  RKE/rancher
- OS (e.g: `cat /etc/os-release`): centos 7.4
- Kernel (e.g. `uname -a`): 3.10.0-693.el7.x86_64
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by iutx** [comment]
@sayicui 从提供的错误上来看是 erda-operator 创建初始化任务失败导致的

**Comment by iutx** [comment]
@sayicui 从提供的错误上来看是 erda-operator 创建初始化任务失败导致的。
麻烦提供下 如下 job 的信息
```shell
kubectl get job -n erda-system erda-init-image -o yaml 
```

**Comment by Cuisayi** [comment]
> 
`apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2021-12-05T08:12:59Z"
  labels:
    controller-uid: 20401ac9-2a1d-436e-beb3-44adc9e260e1
    job-name: erda-init-image
  name: erda-init-image
  namespace: erda-system
  ownerReferences:
  - apiVersion: erda.terminus.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Erda
    name: erda
    uid: b07c43ff-901d-4770-920e-4972080de4b9
  resourceVersion: "27264"
  uid: 20401ac9-2a1d-436e-beb3-44adc9e260e1
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 20401ac9-2a1d-436e-beb3-44adc9e260e1
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 20401ac9-2a1d-436e-beb3-44adc9e260e1
        job-name: erda-init-image
      name: init-image
      namespace: erda-system
    spec:
      containers:
      - env:
        - name: TZ
          value: Asia/Shanghai
        - name: MIGRATION_DEBUGSQL
          value: "false"
        - name: MIGRATION_MYSQL_DBNAME
          value: erda
        - name: MIGRATION_MYSQL_HOST
          value: erda-mysql.erda-system.svc.cluster.local
        - name: MIGRATION_MYSQL_PASSWORD
          value: password
        - name: MIGRATION_MYSQL_PORT
          value: "3306"
        - name: MIGRATION_MYSQL_USERNAME
          value: erda
        - name: MIGRATION_SKIP_LINT
          value: "true"
        image: registry.erda.cloud/erda/init-image:1.4.0-20211116
        imagePullPolicy: Always
        name: init-image
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: aliyun-registry
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: erda-operator
      serviceAccountName: erda-operator
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/lb
status:
  conditions:
  - lastProbeTime: "2021-12-05T08:36:46Z"
    lastTransitionTime: "2021-12-05T08:36:46Z"
    message: Job has reached the specified backoff limit
    reason: BackoffLimitExceeded
    status: "True"
    type: Failed
  failed: 7
  startTime: "2021-12-05T08:12:59Z"
`

**Comment by liuhaoyang** [comment]
@iutx Do you have any new progress?

**Comment by iutx** [comment]
@Cuisayi please reinstall erda and fetch job (name erda-init-image), please provider job logs.

maybe you need clear pvc or delete namespace erda-system and reinstall.

```shell
kubectl delete pvc -n erda-system `kubectl get pvc -n erda-system | grep erda | awk '{print $1}'`
```
