### ISSUE TITLE
self deployed erda how to get admin password

### ISSUE THREAD

**Issue by hellobiek** [erda-project/erda#3297]
#### What happened:
I have deployed a erda in my local k8s cluster, but I don't know how to found admin account and password

#### What you expected to happen:
show me a away to get admin password

#### How to reproduce it (as minimally and precisely as possible):
no

#### Anything else we need to know?:
no

#### Environment:
- Erda version:1.4
- Kubernetes version (use `kubectl version`):1.21.2
- Cloud provider or hardware configuration: aws
- OS (e.g: `cat /etc/os-release`): ubuntu 18.04
- Kernel (e.g. `uname -a`):  5.4.0-1059-aws

- Network plugin and version (if this is a network-related bug): calio
- Others:

**Comment by hellobiek** [comment]
when I logined in the mysql in erda, I only found a encryptied key in table erda.shsp_user

**Comment by iutx** [comment]
@hellobiek 
Please register a new user with your email.
The first user to create an enterprise is the enterprise administrator

Please refer to steps: https://docs.erda.cloud/1.4/manual/install/helm-install/configuration.html#%E8%AE%BF%E9%97%AE%E5%B9%B3%E5%8F%B0

**Comment by liuhaoyang** [comment]
It seems that the problem has been resolved, I will close this issue first
