### ISSUE TITLE
etcd,mysql,zk提示无法找不到PVC

### ISSUE THREAD

**Issue by njxz** [erda-project/erda#3501]

**Comment by njxz** [comment]
使用的是Redhat 4.8.4，rancher 2.5.11, k8s使用v1.19.16-rancher-1-2版本，helm 3.7.2

通过helm install erda erda/erda部署的Erda集群
出现卡在container create阶段
![图片](https://user-images.githubusercontent.com/16254670/147431785-1de367ce-ad6d-4272-86ee-4c2ed87fef1a.png)

describe出现如下问题，pv,pvc都已经创建并绑定好，但是pod依然无法找到
![图片](https://user-images.githubusercontent.com/16254670/147431762-b223e81c-547e-46f5-80f5-24b68249d88f.png)

**Comment by iutx** [comment]
更换为非 rke 部署方式后成功，后续考虑对 RKE 进行同一测试
/close
