### ISSUE TITLE
怎么编译调试 

### ISSUE THREAD

**Issue by NengNgg** [erda-project/erda#3512]
#### What happened:
make build-image
发现找不到项目根目录cmd/build 文件

希望出一个 怎么编译readme 
#### Environment:
- Erda version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liuhaoyang** [comment]
1. To build the binary files of all services, use `make build-all`
2. To build the binary file of a single service, you need to specify MODULE_PATH. For example, to build openapi service, use `MODULE_PATH=openapi build`, other services are similar
3. To build the docker image of all services, refer to https://github.com/erda-project/erda/pull/3513 ,the image will contain all services
4. To build the image of a single service, you need to specify MODULE_PATH. For example, to build the openapi service image, use `MODULE_PATH=openapi build-image`, other services are similar

**Comment by hellobiek** [comment]
是否可以提供一个可以编译程序的DockerFile，本地编译各种问题编译不过。
