### ISSUE TITLE
构建pipeline的时候，自动推送包到https接口，而不是http接口

### ISSUE THREAD

**Issue by hellobiek** [erda-project/erda#3570]
#### What happened:
pipeline push package failed, err log as belows:

2021-12-30 19:12:58The push refers to repository [10.20.0.200:5000/test-java-demo/test1]
2021-12-30 19:13:08Get https://10.20.0.200:5000/v2/: net/http: TLS handshake timeout

![image](https://user-images.githubusercontent.com/2854520/147747445-60c86c61-5a9c-440a-95d9-a0405bb6d49c.png)

#### What you expected to happen:

use http but not https

#### How to reproduce it (as minimally and precisely as possible):

start a pipeline line

#### Environment:
- Erda version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by iutx** [comment]
@hellobiek 当前版本，请您按照文档去更改构建节点的 docker 配置。可以参照 准备工作 第二点：https://docs.erda.cloud/1.5/manual/install/helm-install/premise.html#%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C 

后续版本我们会替换为 buildkit 构建，无需再去更改 docker 配置

**Comment by hellobiek** [comment]
已经是这样的了，但是还是这样的失败
