### ISSUE TITLE
微服务观测项目的基本设置里可以新建一个devops应用

### ISSUE THREAD

**Issue by blackdogcat** [erda-project/erda#3677]
#### What happened:
微服务观测项目的基本设置里可以新建一个devops应用，对这个应用新建流水线时，报错提示（ 创建流水线失败: 异常 创建流水线失败: 缺少参数 clusterName）
#### What you expected to happen:
应该新建流水线成功，微信群里沟通后，刘浩杨老师说这个是功能上的bug，这个功能不用应该出现，应该隔离起来，看不到才对。
#### How to reproduce it (as minimally and precisely as possible):
1. 新建微服务观测项目
2. 点击微服务观测项目的基本设置，在基本设置里添加应用，
3. 新建好应用后，就可以在 devops 里看到新建的应用，然后编写 pipelie.xml 文件。
4. 对这个应用新建流水线，就会有报错提示（ 创建流水线失败: 异常 创建流水线失败: 缺少参数 clusterName）
#### Anything else we need to know?:
新手理解客观测项目的使用难度太大，我以为客观测的程序对语言是不限的，搞的我一头雾水。请在完善下文档，并在其中体现下 erda 平台可以自动观测到项目，不需要额外配置，但是目前只支持java和nodejs项目。期望能够观测到 python 项目
#### Environment:
- Erda version: 1.4
- Kubernetes version (use `kubectl version`): v1.21.7
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
        NAME="Ubuntu"
        VERSION="18.04.5 LTS (Bionic Beaver)"
        ID=ubuntu
        ID_LIKE=debian
        PRETTY_NAME="Ubuntu 18.04.5 LTS"
        VERSION_ID="18.04"
        HOME_URL="https://www.ubuntu.com/"
        SUPPORT_URL="https://help.ubuntu.com/"
        BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
        PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
        VERSION_CODENAME=bionic
        UBUNTU_CODENAME=bionic
- Kernel (e.g. `uname -a`): 62~18.04.1-Ubuntu SMP Fri Oct 22 21:51:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Effet** [comment]
感谢反馈，经确认最新释出的 1.5 版本已修复此问题，可以升级试一下
