### ISSUE TITLE
安装过程，erda-init-image 出错

### ISSUE THREAD

**Issue by VanLiuZhi** [erda-project/erda#3983]
在执行这个job的时候，一开始应该是连接数据库吧，有以下日志，这个应该算正常

<img width="1704" alt="截屏2022-01-26 22 03 22" src="https://user-images.githubusercontent.com/22883555/151177306-b5e9f1a5-4381-4d80-b327-136ae076bc21.png">

然后做了一些初始化之后，Python相关的报错了，内容如下：
<img width="1695" alt="截屏2022-01-26 22 03 53" src="https://user-images.githubusercontent.com/22883555/151177756-8f7b7fb7-812d-47ee-be5b-8c848265c37b.png">

看情况是Python的问题，看这个报错的意思，需要加一个 -H 才能运行 pip （我的环境全是root用户，我查到的一些资料，好像说Python不推荐root执行pip，不知道会不会是这个问题）

<img width="1493" alt="截屏2022-01-26 22 13 11" src="https://user-images.githubusercontent.com/22883555/151178958-aef4a6de-294d-47ea-8970-d863d8a0291d.png">
                           
我该如何排查这个问题呢，我看了mysql的pod，都是正常的。

请问这个erda-init-image的相关代码是哪个，我想去看看源码好分析一下问题。

部署环境：
centos 7.4 内核3.10，测试了1.5 和 1.4 都存在这个问题。

**Comment by VanLiuZhi** [comment]
是要去联网下载东西吧，pip 要去安装依赖，是这样的逻辑吧

**Comment by iutx** [comment]
@VanLiuZhi 当前 migration 工具设计存在根据开发者提供的 migration 中定义的 requirements.txt 安装的逻辑。后续会在 init-image 构建的时候 ready，做到离线化

**Comment by iutx** [comment]
相关离线化已经修复，会随下个 Erda 版本发布。

**Comment by VanLiuZhi** [comment]
@iutx 这块相关的源码，大致是哪个项目里面呢？我现在有点难处理，我宿主机可以通过配置proxy代理，请求到pip源的地址，但是运行的容器则没有。
目前我有两个想法：
1. 找到源码，看看有没有什么可以调整的
2. 导入erda-init-image的job yaml，修改注入http_proxy环境变量。是不是在依赖组件都ok的情况下，这个job任务就会把整个erda的相关的组件一步步安装完成

**Comment by iutx** [comment]
@VanLiuZhi 这块我这边提供给您一个镜像吧，您这边可以 pull 下来 chart，然后更改里面的镜像就好
```shell
helm pull
```
