### ISSUE TITLE
go应用初始化的时候，go proxy的原因导致初始化失败

### ISSUE THREAD

**Issue by njxz** [erda-project/erda#4043]
![图片](https://user-images.githubusercontent.com/16254670/153990928-985504ed-a196-408a-830c-89a444bac088.png)
通过pipeline配置了envs 不生效
![图片](https://user-images.githubusercontent.com/16254670/153991006-87d1d452-29c3-4480-91f0-5f465fe15a8a.png)

**Comment by chengjoey** [comment]
> ![图片](https://user-images.githubusercontent.com/16254670/153990928-985504ed-a196-408a-830c-89a444bac088.png) 通过pipeline配置了envs 不生效 ![图片](https://user-images.githubusercontent.com/16254670/153991006-87d1d452-29c3-4480-91f0-5f465fe15a8a.png)

这个应该是生效了吧，GOPROXY改成`https://goproxy.io,direct试下
