### ISSUE TITLE
单机部署(v1.5.0)，初次创建项目失败(failed to parse userID)

### ISSUE THREAD

**Issue by dssy** [erda-project/erda#4057]
<img width="1887" alt="图片" src="https://user-images.githubusercontent.com/17376435/154184095-cad8547b-8451-4ff1-8d1a-b10985815b2f.png">

**Comment by jiagf-personal** [comment]
我们用docker-compose安装的单机版，用官网给的quick-start.sh安装的
初次建项目遇到了同样的问题
报错一样的，也是解析不了用户ID

**Comment by jiagf-personal** [comment]
单机版能装1.6吗？

**Comment by snakorse** [comment]
@dssy @jiagf-personal  this bug has been fixed in v2.0.0 . try the command bellow to install v2.0.0:

`/bin/bash -c "$(curl -fsSL https://static.erda.cloud/quick-start/2.0.0/quick-start.sh)"`
