### ISSUE TITLE
what' s the username/password of erda created by helm installing

### ISSUE THREAD

**Issue by edisonwong520** [erda-project/erda#4577]
hi , I started with helm installation(https://docs.erda.cloud/en/2.0/manual/install/helm-install/helm-install-demo.html) ,but i cannot sign up.I try another way to login with an existed user account and i found some user records in MySQL erda DATABASE uc_user TABLE 
so what's the password of 'gittar' etc...

**Comment by edisonwong520** [comment]
thanks all guys if you can provide an username/password ,so i can try and play in erda demo

**Comment by shuofan** [comment]
hi @edisonwong520, signup is required with helm installation. The existing users like 'gittar' are inner users which cannot be used for login.  Feel free to post screenshots about your problems during the registration.
