### ISSUE TITLE
这么喜欢搞全家桶

### ISSUE THREAD

**Issue by livesiteme** [erda-project/erda#464]
……

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by sfwn** [comment]
Duplicated issue, please see #260

**Comment by Effet** [comment]
we are working on separating modules, and soon release new version, you can run single module like DOP then.

i will close this duplicated issue, feel free arise a new issue if you have other question.

hope you can use english because our community is international, thank you!
