### ISSUE TITLE
 cannot find module providing package github.com/erda-project/erda/tools/cli/generated_cmd

### ISSUE THREAD

**Issue by zhangalbert** [erda-project/erda#4668]
你好，这个代码项进行二次开发，make -f Makefile 报错，缺少 cmd 生成器，请问怎么编译程序，官网似乎没有相关开发文档
这个工程用的echo web开发框架

**Comment by sfwn** [comment]
你好，可以使用 `make prepare` 生成相关代码，然后进行二次开发。
