### ISSUE TITLE
我想只使用微服务治理平台可以吗

### ISSUE THREAD

**Issue by Phoebus888** [erda-project/erda#4677]
不接入devops  怎么接入微服务治理平台

**Comment by innerpeacez** [comment]
https://docs.erda.cloud/2.0/manual/msp/guides/platform/msp-project.html#%E7%9B%91%E6%8E%A7%E9%A1%B9%E7%9B%AE%E6%8E%A5%E5%85%A5 @Phoebus888

**Comment by innerpeacez** [comment]
java 可以也可使用 Erda java agent https://github.com/erda-project/erda-java-extensions
