### ISSUE TITLE
Join the cluster, display the node memory resource error

### ISSUE THREAD

**Issue by fanghc123** [erda-project/erda#493]
After adding the cluster, it is found that the memory resource of the display server is too small, which is not equal to the actual memory resource.

**Comment by fanghc123** [comment]
After adding the cluster, it is found that the memory resource of the display server is too small, which is not equal to the actual memory resource.

#### Environment:
- Erda version: v1.0.0-rc
- Kubernetes version (use `kubectl version`): v1.16.14
- Cloud provider or hardware configuration: aliyun  8C 64G
- OS (e.g: `cat /etc/os-release`): Alibaba Group Enterprise Linux Server
- Kernel (e.g. `uname -a`): 3.10.0-327.ali2019.alios7.x86_64

**Comment by luobily** [comment]
cc @liuhaoyang

**Comment by Muzry** [comment]
Thanks, @fanghc123, How can I download the operating system named  `Alibaba Group Enterprise Linux Server`, and how many `memory resources` display on the Erda?

> After adding the cluster, it is found that the memory resource of the display server is too small, which is not equal to the actual memory resource.
> 
> #### Environment:
> * Erda version: v1.0.0-rc
> * Kubernetes version (use `kubectl version`): v1.16.14
> * Cloud provider or hardware configuration: aliyun  8C 64G
> * OS (e.g: `cat /etc/os-release`): Alibaba Group Enterprise Linux Server
> * Kernel (e.g. `uname -a`): 3.10.0-327.ali2019.alios7.x86_64
