### ISSUE TITLE
Hello, I am a personal developer. I recently read erda open source and would like to ask if there is a deployment tutorial. I personally want to study the erda source code

### ISSUE THREAD

**Issue by Jtanfa** [erda-project/erda#527]
Hello, I am a personal developer. I recently read erda open source and would like to ask if there is a deployment tutorial. I personally want to study the erda source code

**Comment by Muzry** [comment]
Hi @Jtanfa  the tutorial of deployment is here:
https://github.com/erda-project/erda/blob/master/docs/guides/deploy/How-to-install-the-Erda.md

**Comment by Jtanfa** [comment]
@Muzry thanks

**Comment by Jtanfa** [comment]
In addition, I am a personal developer, and the hardware configuration may not meet the standard. Is each node of 4C16G necessary?

**Comment by Muzry** [comment]
> In addition, I am a personal developer, and the hardware configuration may not meet the standard. Is each node of 4C16G necessary?

According to our test,  the current Erda version requires at least 4 nodes, and each node requires  4C16G. we are trying to reduce the resources of each component so that you can deployment the Erda on your local machine in the future.

**Comment by Jtanfa** [comment]
thanks  I got it
