### ISSUE TITLE
node版本不支持16么？

### ISSUE THREAD

**Issue by luoluo2001108** [erda-project/erda#5665]
node版本填16，流水线打包报错，12版本流水线打包正常
我看之前说明是16版本支持的，请帮忙确认一下是什么原因？

错误日志如下

2023-01-11 10:39:28change workding directory to: /.pipeline/container/context/git-checkout
2023-01-11 10:39:28 not support this node version 16 
2023-01-11 10:39:28

流水线配置如下：
- stage:
      - js-build:
          alias: js-build
          description: 针对 nodejs 工程的编译打包任务
          version: "1.0"
          params:
            build_cmd:
              - npm config set registry=https://registry.npmmirror.com
              - npm i
              - npm run build
              - cp  -r /.pipeline/container/context/git-checkout/dist /.pipeline/context/git-checkout/
            node_version: 16
            workdir: ${git-checkout}

**Comment by chengjoey** [comment]
可以确认下js-build action用的是否为最新镜像
新的js-build确实已经支持node 16版本了
[update node version and support node@16](https://github.com/erda-project/erda-actions/pull/398)

看这个issue应该主要是扩展市场的问题，action方面的问题欢迎到[erda-actions仓库](https://github.com/erda-project/erda-actions)提相关issue

**Comment by chengjoey** [comment]
看到已在actions仓库建立相关[issue](https://github.com/erda-project/erda-actions/issues/505)
这里先进行关闭，有其他问题也请随时打开
