### ISSUE TITLE
用文档里的基于docker compose安装脚本访问失效，.sh脚本资源访问404

### ISSUE THREAD

**Issue by hyback2u** [erda-project/erda#6100]
这块：
https://docs.erda.cloud/2.2/manual/install/docker-install.html

```shell
/bin/bash -c "$(curl -fsSL https://static.erda.cloud/quick-start/quick-start.sh)"

**Comment by hyback2u** [comment]
z

**Comment by sfwn** [comment]
Please use: https://github.com/erda-project/erda-release/blob/master/quick-start/build_quickstart.sh

**Comment by hyback2u** [comment]
> 请使用：[https ://github.com/erda-project/erda-release/blob/master/quick-start/build_quickstart.sh](https://github.com/erda-project/erda-release/blob/master/quick-start/build_quickstart.sh)

![image](https://github.com/erda-project/erda/assets/42307653/64db9c17-2b00-41cc-b5c4-6fb6502197a0)

**Comment by hyback2u** [comment]
你点下看看

**Comment by git2017-jpg** [comment]
> 你点下看看

这个里面好像还是1.3.0的版本
