### ISSUE TITLE
一条流水线可以部署一个工程目录下的多个服务，可以实现吗

### ISSUE THREAD

**Issue by luoluo2001108** [erda-project/erda#6461]
您好:
   我们有一个需求，就是需要一条流水线可以部署一个工程目录下的多个服务，可以实现吗？
   这里的releaseID不知道能不能填数组。。

 - stage:
      - dice:
          alias: dice-auth
          description: 用于 Erda 平台部署应用服务
          params:
            release_id: ${release-log:OUTPUT:releaseID}

期待您的回复，谢谢

**Comment by sfwn** [comment]
可以使用多个 app-run action。

参考：https://www.erda.cloud/market/action/app-run
