### ISSUE TITLE
clone太慢了，到码云做个镜像吧

### ISSUE THREAD

**Issue by wangpeng0824** [erda-project/erda#699]
clone太慢了，到码云做个镜像吧

**Comment by QvodSoldier** [comment]
We are considering

**Comment by sixther-dc** [comment]
https://gitee.com/erda-project/erda

**Comment by sixther-dc** [comment]
https://gitee.com/erda-project/erda

**Comment by sixther-dc** [comment]
https://gitee.com/erda-project/erda  
We have created a mirror repo in gitee.com, but it is not synchronized in real time, We are still working on it. @wangpeng0824

**Comment by wangpeng0824** [comment]
> https://gitee.com/erda-project/erda
> We have created a mirror repo in gitee.com, but it is not synchronized in real time, We are still working on it. @wangpeng0824

nice！
