### ISSUE TITLE
多云管理平台导入自建kubernetes集群后，只显示master节点信息，无work node节点相关信息

### ISSUE THREAD

**Issue by wake-lee** [erda-project/erda#704]
#### What happened:
多云管理平台导入自建kubernetes集群后，只显示master节点信息，无work node节点相关信息，添加kubernetes中work node节点时，操作窗口卡死无响应
#### Environment:
- Erda version:v1.0.0
- Kubernetes version (use `kubectl version`):v1.18.4
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):centos7.6 1810
- Kernel (e.g. `uname -a`):3.10.0-957.el7.x86_64
- Network plugin and version (if this is a network-related bug):calico v3.8.6
- Others:

**Comment by sixther-dc** [comment]
@wake-lee Does your kubernetes cluster only have master nodes？  then you want to add nodes by erda。

**Comment by wake-lee** [comment]
> @wake-lee你的kubernetes集群是只有master节点吗？那你想通过erda来添加节点。
我的k8s集群是1主3work node，在erda平台导入k8s集群后，猜想：原本erda平台应该会显示k8s集群所有节点信息，但是erda平台只显示master一个节点信息。于是，通过erda平台添加work node节点信息，结果此操作卡死无响应。

**Comment by wake-lee** [comment]
@sixther-dc 我的k8s集群是1主3work node，在erda平台导入k8s集群后，猜想：原本erda平台应该会显示k8s集群所有节点信息，但是erda平台只显示master一个节点信息。于是，通过erda平台添加work node节点信息，结果此操作卡死无响应。

**Comment by sixther-dc** [comment]
@wake-lee  Do you labeled all nodes with your created organization name not only master node ？

**Comment by wake-lee** [comment]
> @wake-lee 你是不是只用你创建的组织名称标记了所有节点，而不仅仅是主节点？

@sixther-dc 嗯，是你说的这个原因，目前已经解决了，非常感谢！

**Comment by wake-lee** [comment]
问题已解决，集群所有节点需要执行：
