### ISSUE TITLE
部署说明中关于helm install，需要提示请到主目录中

### ISSUE THREAD

**Issue by c4fun** [erda-project/erda#707]
#### What happened:
按照[此安装说明](https://github.com/erda-project/erda/blob/master/docs/guides/deploy/How-to-install-Erda-zh.md)来安装，在**安装**子章节的第3步中，有一个通过 Helm 安装 Erda Helm 包的步骤，但是直接输入helm install 命令会报以下错误:

```
# helm install package/erda-base-0.1.0.tgz --generate-name
Error: failed to download "package/erda-base-0.1.0.tgz" (hint: running `helm repo update` may help)
```

#### What you expected to happen:

期望安装成功。

这里是因为必须在erda这个文件夹中进行安装导致的。而安装途中变更了目录。

#### How to reproduce it (as minimally and precisely as possible):

安装好k8s之后，按照[此安装说明](https://github.com/erda-project/erda/blob/master/docs/guides/deploy/How-to-install-Erda-zh.md)进行操作即可。

#### Environment:
- Erda version: v1.0.0
- Kubernetes version (use `kubectl version`): v1.21.0
- Cloud provider or hardware configuration: tencent cloud
- OS (e.g: `cat /etc/os-release`): centos 7.9
- Kernel (e.g. `uname -a`): 3.10.0-1160.11.1.el7.x86_64
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by sixther-dc** [comment]
@Muzry

**Comment by sixther-dc** [comment]
> #### What happened:
> 按照[此安装说明](https://github.com/erda-project/erda/blob/master/docs/guides/deploy/How-to-install-Erda-zh.md)来安装，在**安装**子章节的第3步中，有一个通过 Helm 安装 Erda Helm 包的步骤，但是直接输入helm install 命令会报以下错误:
> 
> ```
> # helm install package/erda-base-0.1.0.tgz --generate-name
> Error: failed to download "package/erda-base-0.1.0.tgz" (hint: running `helm repo update` may help)
> ```
> 
> #### What you expected to happen:
> 期望安装成功。
> 
> 这里是因为必须在erda这个文件夹中进行安装导致的。而安装途中变更了目录。
> 
> #### How to reproduce it (as minimally and precisely as possible):
> 安装好k8s之后，按照[此安装说明](https://github.com/erda-project/erda/blob/master/docs/guides/deploy/How-to-install-Erda-zh.md)进行操作即可。
> 
> #### Anything else we need to know?:
> #### Environment:
> * Erda version: v1.0.0
> * Kubernetes version (use `kubectl version`): v1.21.0
> * Cloud provider or hardware configuration: tencent cloud
> * OS (e.g: `cat /etc/os-release`): centos 7.9
> * Kernel (e.g. `uname -a`): 3.10.0-1160.11.1.el7.x86_64
> * Network plugin and version (if this is a network-related bug):
> * Others:

@Muzry

**Comment by Muzry** [comment]
Thanks for your advice, I will fix this issue immediately.
