### ISSUE TITLE
添加集群报错

### ISSUE THREAD

**Issue by liuflylove666** [erda-project/erda#867]
#### Environment:
- Erda version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Network plugin and version (if this is a network-related bug):
- Others:
添加集群报错：
添加已有资源自建集群
异常 get cloud resource context failed, err:<nil>

**Comment by luobily** [comment]
是使用了 “添加已有资源自建集群” 的功能？ 报错信息还有更详细的么？

**Comment by luobily** [comment]
可以在 “集群管理 / 操作历史” 中，查看操作日志。

**Comment by Muzry** [comment]
请使用导入已有 k8s 集群试一下，配置信息请按照集群入口信息请填写 inet://ingress-nginx.kube-system.svc.cluster.local?direct=on&ssl=on/kubernetes.default.svc.cluster.local
